db.url=jdbc:postgresql://localhost:5432/postgres
db.username=postgres
db.password=mugivara25
spring.thymeleaf.prefix=classpath:/WEB-INF/views/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false  # Optional, disable caching during development